# Project Information
site_name: Hüpftronik Documentation
site_description: Open-source hardware solutions for automotive and motorcycle projects.
site_author: Hüpftronik
site_url: https://martijn4313.github.io/hupftronik-docs/
use_directory_urls: true

# Theme Configuration
theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: deep orange
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight


extra_css:
  - stylesheets/extra.css
  
extra_javascript:
  - javascripts/mathjax-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  
# Navigation Tree
nav:
  - Home: index.md
  - Products:
    - Motorsteuergerät 24P V1:
      - Overview & Specs: products/motorsteuergerat-24p-v1/24p_v1_overview.md
      - Hardware & Wiring: products/motorsteuergerat-24p-v1/wiring.md
      - Design Reference: products/motorsteuergerat-24p-v1/reference.md
      - Setup guide:
        - Setup Overview: products/motorsteuergerat-24p-v1/setup/index.md
        - Flashing the PCB: products/motorsteuergerat-24p-v1/setup/flashing.md
        - rusEFI Guide: products/motorsteuergerat-24p-v1/setup/rusefi.md
        - Speeduino Guide: products/motorsteuergerat-24p-v1/setup/speeduino.md
      
  - Guides:
     - Planning your build: guides/setup/planning.md
     - Tuning Basics: guides/tuning/basics.md
     - Software Tools (TunerStudio): guides/tuning/software.md
     - CAN Bus Basics: guides/tuning/canbus-basics.md
     - Troubleshooting: guides/setup/troubleshooting.md

     - Vehicle specific setup guides:
        - Volvo B2xx Redblock: guides/setup/specific/volvo-b2xx.md
        - Peugeot TU Series: guides/setup/specific/peugeot-tu.md
        - Renault F4R: guides/setup/specific/renault-f4r.md
        - Mini A-Series: guides/setup/specific/mini-a-series.md
        - Volkswagen 1.8T: guides/setup/specific/vw-1.8t.md

     - Conversion Guides:
        - MegaSquirt to Motorsteuergerät 24P V1: guides/conversions/ms-to-24p.md

  - About:
    - Our Philosophy: about/philosophy.md
    - Open-Source & Community: about/community.md
    - License & Disclaimer: about/license.md

  
#    - Schildknappe (CAN Node):
#      - Overview & Specs: products/schildknappe/index.md
#      - Hardware & Wiring: products/schildknappe/wiring.md
#      - Firmware Setup:
#        - Setup Overview: products/schildknappe/setup/index.md
#        - Flashing the PCB: products/schildknappe/setup/flashing.md
#        - rusEFI Guide: products/schildknappe/setup/rusefi.md
#        - Speeduino Guide: products/schildknappe/setup/speeduino.md
#      - Standalone Operation: products/schildknappe/standalone.md
#      - Hardware Reference: products/schildknappe/reference.md


